### ISSUE TITLE
New GMF username and PARQ

### ISSUE THREAD

**Issue by kourilm83** [Get-Me-Fit/getmefit-mobile#3]
**Given** I logged in
**When** I am the first time user of GMF
**Then** I have to enter my new username
**and** I have to finish the Physical Activity Readiness Questionnaire

Useful links:
Read this thread on slack: https://getmefitco.slack.com/archives/C010HCXQXTR/p1584898712037200?thread_ts=1584898529.036400&cid=C010HCXQXTR

**Comment by kourilm83** [comment]
Please read the questions below:
1. Has your doctor ever said that you have a heart condition and that you should only do physical activity recommended by a doctor?
2. Do you feel pain in your chest when you do physical activity?
3. In the past month, have you had chest pain when you were not doing physical activity?
4. Do you lose your balance because of dizziness or do you ever lose consciousness?
5. Do you have a bone or joint problem that could be made worse by a change in your physical activity?
6. Is your doctor currently prescribing drugs (for example, water pills) for your blood pressure or heart condition?
7. Do you know of any other reason why you should not do physical activity?

**Comment by kourilm83** [comment]
If you answered "yes" to one or more questions, talk with your doctor before you start becoming much more active or before you have a fitness test. Tell your doctor about the PAR-Q and which questions you answered "yes".

**Comment by kourilm83** [comment]
![IMG_20200324_195837 (1)](https://user-images.githubusercontent.com/6277413/77466243-44ba2680-6e0a-11ea-8825-4c070835a2d6.jpg)

**Comment by edgarfgp** [comment]
Is this the related design ? 

<img width="650" alt="Screenshot 2020-03-24 at 20 02 34" src="https://user-images.githubusercontent.com/31915729/77466343-6c10f380-6e0a-11ea-89fb-02a0fffc789f.png">

**Comment by kourilm83** [comment]
yes

**Comment by edgarfgp** [comment]
Ok I will start working on this one

**Comment by edgarfgp** [comment]
There is PR in place for this issue #9
